#!/usr/bin/env ruby

require 'pomodoro/commands'
require 'refined-refinements/colours'

using RR::ColouredTerminal

puts Pomodoro::Commander.commands.map { |key, cmd|
  next unless cmd.description
  "#{key}:#{cmd.description.gsub("'", "''")}"
}.compact.join("\n")
